Traceback (most recent call last):
  File "/home/runner/local/lib/python3.13/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
    ~~~~~~~~~^
        nb,
        ^^^
    ...<4 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "/home/runner/local/lib/python3.13/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/runner/local/lib/python3.13/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/home/runner/local/lib/python3.13/asyncio/base_events.py", line 725, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/home/runner/local/lib/python3.13/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
        cell, index, execution_count=self.code_cells_executed + 1
    )
  File "/home/runner/local/lib/python3.13/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/local/lib/python3.13/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# The Taylor integrator
ta = pk.ta.get_pc(1e-16)
# The Hamiltonian
H_func = pk.ta.get_pc_H_cfunc()
# The switching function
SF_func = pk.ta.get_pc_SF_cfunc()
# The magnitude of the throttle
u_func = pk.ta.get_pc_u_cfunc()
# The thrust direction
i_vers_func = pk.ta.get_pc_i_vers_cfunc()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[10], line 2[0m
[1;32m      1[0m [38;5;66;03m# The Taylor integrator[39;00m
[0;32m----> 2[0m ta [38;5;241m=[39m [43mpk[49m[38;5;241;43m.[39;49m[43mta[49m[38;5;241;43m.[39;49m[43mget_pc[49m[43m([49m[38;5;241;43m1e-16[39;49m[43m)[49m
[1;32m      3[0m [38;5;66;03m# The Hamiltonian[39;00m
[1;32m      4[0m H_func [38;5;241m=[39m pk[38;5;241m.[39mta[38;5;241m.[39mget_pc_H_cfunc()

[0;31mTypeError[0m: _get_pc(): incompatible function arguments. The following argument types are supported:
    1. (tol: float, optimality: pykep.core.optimality_type) -> heyoka::v34::taylor_adaptive<double>

Invoked with: 1e-16

